# Site settings
title: Taylor's Heap
email: taylorwood@me.com
description: A programmer in Chicago, IL.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://taylorwood.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  taylorwood

# Build settings
markdown: kramdown
